slide_contents:
  - filename: 2494974941_3e115fc42f_b.jpg
    message:
      lt: "{{name}}さんのLT、聞きたいなぁ"
      congratulations: "{{name}}さんが、当たり!"
    text_position: bottom
    text_color: white
  - filename: 2187242989_2eacb23b1e_b.jpg
    message:
      lt: "{{name}}さん、ちょっとLTしてくれないかね?"
      congratulations: "{{name}}さん、当選。"
    text_position: bottom
    text_color: white
  - filename: 7765050482_d261f1a0f7_b.jpg
    message:
      lt: "{{name}}さん、LTしてくれないと引っかくぞ〜?"
      congratulations: "{{name}}さんに当てといてやった"
    text_position: top
    text_color: white
  - filename: 8544790758_393427f0c3_k.jpg
    message:
      lt: "{{name}}さんのLTどこ?"
      congratulations: "Congratulations dear {{name}}!"
    text_position: top
    text_color: white
  - filename: 6672150457_420d61007d_b.jpg
    message:
      lt: "{{name}}さんのLT、待ちくたびれた..."
      congratulations: "{{name}}さんに、きめた!"
    text_position: top
    text_color: white
  - filename: 6866446860_2efb9b7e7c_k.jpg
    message:
      lt: "{{name}}さんのLT聞きに来たよ!"
      congratulations: "{{name}}さんに当たりのお知らせ!"
    text_position: bottom
    text_color: white
  - filename: 1460135828_2afcc1cf35_b.jpg
    message:
      lt: "{{name}}さん、同情するならLTをくれ"
      congratulations: "{{name}}さん、当たりの分け前は?"
    text_position: bottom
    text_color: white
  - filename: 256249222_f4c8375c29_b.jpg
    message:
      lt: "{{name}}さんLT、きっと素敵だろうなぁ…"
      congratulations: "当たりは{{name}}さんです"
    text_position: bottom
    text_color: white
  - filename: 4154543904_6e2428c421_b.jpg
    message:
      lt: "{{name}}さんのLTまだ〜?"
      congratulations: "{{name}}さん、当たったよ〜"
    text_position: bottom
    text_color: white
  - filename: 560380352_8b58b0611c_o.jpg
    message:
      lt: "{{name}}さん、LT!! LT!!"
      congratulations: "{{name}}さん、当たり!!当たり!!"
    text_position: bottom
    text_color: white
  - filename: 3970746529_4942479359_b.jpg
    message:
      lt: "{{name}}さん、LTしてくれないと食べちゃうよ?"
      congratulations: "{{name}}さん、当てちゃったね…?"
    text_position: top
    text_color: white
  - filename: 3426033125_455e921468_b.jpg
    message:
      lt: "{{name}}さん、LTしてくれないの…?"
      congratulations: "{{name}}さん、当たりですよ〜"
    text_position: top
    text_color: white
  - filename: 8117203851_6f8eb22a89_k.jpg
    message:
      lt: "{{name}}さん、なにとぞ我が輩にLTを…"
      congratulations: "{{name}}さん、我が輩が当選の使者だ"
    text_position: bottom
    text_color: white
  - filename: 166632865_cca01e7aa9_o.jpg
    message:
      lt: "{{name}}さん、ちょっと暇なんでLTしてくれる?"
      congratulations: "{{name}}さん、当たったの? ふーん…。"
    text_position: bottom
    text_color: gray
  - filename: 7905697728_efe99fd1ae_k.jpg
    message:
      lt: "{{name}}さんのLT、待ってる!!"
      congratulations: "{{name}}さん、おめでとうございます!"
    text_position: top
    text_color: white
