slide_contents:
  - filename: 2494974941_3e115fc42f_b.jpg
    message: "{{name}}さんのLT、聞きたいなぁ"
  - filename: 2187242989_2eacb23b1e_b.jpg
    message: "{{name}}さん、ちょっとLTしてくれないかね?"
  - filename: 7765050482_d261f1a0f7_b.jpg
    message: "{{name}}さん、LTしてくれないと引っかくぞ〜?"
  - filename: 8544790758_393427f0c3_k.jpg
    message: "{{name}}さんのLTどこ?"
  - filename: 6672150457_420d61007d_b.jpg
    message: "{{name}}さんのLT、待ちくたびれた..."
  - filename: 6866446860_2efb9b7e7c_k.jpg
    message: "{{name}}さんのLT聞きに来たよ!"
  - filename: 1460135828_2afcc1cf35_b.jpg
    message: "{{name}}さん、同情するならLTをくれ"
  - filename: 256249222_f4c8375c29_b.jpg
    message: "{{name}}さんLT、きっと素敵だろうなぁ…"
  - filename: 4154543904_6e2428c421_b.jpg
    message: "{{name}}さんのLTまだ〜?"
  - filename: 560380352_8b58b0611c_o.jpg
    message: "{{name}}さん、LT!! LT!!"
  - filename: 3970746529_4942479359_b.jpg
    message: "{{name}}さん、LTしてくれないと食べちゃうよ?"
  - filename: 3426033125_455e921468_b.jpg
    message: "{{name}}さん、LTしてくれないの…?"
  - filename: 8117203851_6f8eb22a89_k.jpg
    message: "{{name}}さん、なにとぞ我が輩にLTを…"
  - filename: 166632865_cca01e7aa9_o.jpg
    message: "{{name}}さん、ちょっと暇なんでLTしてくれる?"
  - filename: 7905697728_efe99fd1ae_k.jpg
    message: "{{name}}さんのLT、待ってる!!"
